# Generated by Django 2.2.5 on 2019-09-17 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=20, unique=True)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.type_id')),
                ('municipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locality.municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
