# Generated by Django 2.2.5 on 2019-09-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='tb_principa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=20)),
                ('column2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tb_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=12)),
                ('tb_foren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testDb.tb_2')),
            ],
        ),
        migrations.AddField(
            model_name='tb_2',
            name='tb_foren',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testDb.tb_principa'),
        ),
    ]
