# Generated by Django 2.2.5 on 2019-09-17 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locality.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dane', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=70)),
                ('details', models.TextField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locality.municipio')),
            ],
        ),
    ]
